export enum RigidBodyFlags {
    None = 0,
    KINEMATIC = 1,
    USE_KINEMATIC_TARGET_FOR_SCENE_QUERIES = 2,
    ENABLE_CCD = 4,
    ENABLE_CCD_FRICTION = 8,
    ENABLE_POSE_INTEGRATION_PREVIEW = 16,
    ENABLE_SPECULATIVE_CCD = 32,
    ENABLE_CCD_MAX_CONTACT_IMPULSE = 64,
    RETAIN_ACCELERATIONS = 128
}